apiVersion: apps/v1
kind: Deployment
metadata:
  name: ue
  namespace: open5gs
  labels:
    app: ue

spec:
  replicas: 1
  selector:
    matchLabels:
      app: ue

  template:
    metadata:
      labels:
        app: ue

    spec:
      containers:
      - name: ueransim
        image: free5gc/ueransim:latest
        imagePullPolicy: Always
        command:
        - /ueransim/nr-ue
        - -c
        - /ueransim/config/open5gs-ue.yaml

        volumeMounts:
        - name: config
          mountPath: /ueransim/config

      volumes:
      - name: config
        configMap:
          name: ueransim-config

